spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    show-sql: 'true'
  datasource:
    url: jdbc:mysql://localhost:3306/crmdb
    username: root
    password: Pratham@1

server:
  port: 3051